### PR TITLE
fix(build): remove sourceMappingURL from svelte build

### LINKED ISSUE #27: [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query...
I'm using for the first time `svelte-query` and for the first time too `svelte-kit`.

I'm having these warnings/errors in console everytime I start my project:

```
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queryClientProvider/QueryClientProvider.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/query/Query.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/infiniteQuery/InfiniteQuery.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queries/Queries.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isMutating/IsMutating.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isFetching/IsFetching.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/hydration/Hydrate.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/mutation/Mutation.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queryClientProvider/QueryClientProvider.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/query/Query.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/infiniteQuery/InfiniteQuery.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queries/Queries.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isFetching/IsFetching.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isMutating/IsMutating.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/mutation/Mutation.svelte.
[vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/hydration/Hydrate.svelte.
```

Why?

### PR DESCRIPTION
**Pull request by SomaticIT**
Hi,

This lib is excellent, I use it on a real world project and it helps a lot with query management.

After a couple of month using it, I have few suggestions and feedbacks about the lib.
I will try to help by contributing with some PRs.

Here is the first one.

During the build, this lib preprocess svelte files before packaging but the typescript preprocessor is relying on the `tsconfig.json` base file of the project so it produces sourceMaps files (which are not exported).

This PRs fixes that behavior by passing the typescript preprocessor the good file to use.

Fixes #27

### CODE REVIEW

**Comment by frederikhors** [comment]
**This is extremely useful!**

**Review by amen-souissi — APPROVED** [review]

**Comment by amen-souissi** [comment]
Yes. 🙏

**Comment by SomaticIT** [comment]
Thanks @amen-souissi for merging this.

**Comment by frederikhors** [comment]
@amen-souissi can you please release this?

**Comment by frederikhors** [comment]
@amen-souissi I can help you release this. You can give me permissions and I'll do it asap. 😃

**Comment by amen-souissi** [comment]
V1.3.2

**Pull request merged**
